version: '2.1'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    container_name: mrm_redis
  app:
    restart: always
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    ports:
      - '5000:8000'
    expose:
      - '5000'
    volumes:
      - ${PWD}:/app
    stdin_open: true
    tty: true
    container_name: push_service
